### ISSUE TITLE
Error when opening jar

### ISSUE THREAD

**Issue by EricLottman** [deltacv/EOCV-Sim#109]
Error when opening jar

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/github/serivesmejia/eocvsim/Main has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:621)

Windows 11 Home 22H2 (build 22621.3007)
Java 8 Version 401 (build 1.8.0_401-b10)
x64 processor
EOCV-Sim-3.5.2-all.jar

**Comment by serivesmejia** [comment]
Apologies for the very delayed response, I became inactive as i was dealing with end-of-highschool stuff.
Regardless, you need Java 10 at minimum to run newer versions of EOCV-Sim! That's what the exception is referring to. It seems from your info that you were using Java 8. If you have any further issues don't hesitate to open a new one.
