### ISSUE TITLE
Unable to run EOCV-Sim on Macbook with Apple M1 chip

### ISSUE THREAD

**Issue by ssnagar** [deltacv/EOCV-Sim#77]
**Describe the bug**
It appears that EOCV-Sim is not compatible with Apple M1 chip. 

**To Reproduce**
Run the application on the Terminal using the command java -jar "/Applications/EOCV-Sim-3.3.2-all.jar"

**Expected behavior**
The application should run so that I can link it with my FTC code

**Screenshots**
Last login: Fri Dec 10 10:52:20 on ttys000
suds@xxxx ~ % java -jar "/Applications/EOCV-Sim-3.3.2-all.jar"
00:00  INFO: [LockFile] Probably locked file /Users/suds/.eocvsim/.lock
00:00  INFO: [EOCVSim] Confirmed claiming of the lock file in /Users/suds/.eocvsim

00:00  INFO: [EOCVSim] Initializing EasyOpenCV Simulator v3.3.2 (2bbaf4f0)

00:00  INFO: [EOCVSim] Loading native lib...
00:00 ERROR: [EOCVSim] Failure loading the OpenCV native lib
java.lang.ExceptionInInitializerError
	at nu.pattern.OpenCV$LocalLoader.getInstance(OpenCV.java:340)
	at nu.pattern.OpenCV.loadLocally(OpenCV.java:323)
	at com.github.serivesmejia.eocvsim.EOCVSim$Companion.loadOpenCvLib(EOCVSim.kt:79)
	at com.github.serivesmejia.eocvsim.EOCVSim.init(EOCVSim.kt:152)
	at com.github.serivesmejia.eocvsim.EOCVSimCommandInterface.run(Main.kt:65)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at com.github.serivesmejia.eocvsim.Main.main(Main.kt:17)
Caused by: nu.pattern.OpenCV$UnsupportedPlatformException: Operating system "OSX" and architecture "ARMv8" are not supported.
	at nu.pattern.OpenCV.extractNativeBinary(OpenCV.java:381)
	at nu.pattern.OpenCV.extractNativeBinary(OpenCV.java:350)
	at nu.pattern.OpenCV.access$100(OpenCV.java:23)
	at nu.pattern.OpenCV$LocalLoader.<init>(OpenCV.java:329)
	at nu.pattern.OpenCV$LocalLoader.<init>(OpenCV.java:326)
	at nu.pattern.OpenCV$LocalLoader$Holder.<clinit>(OpenCV.java:336)
	... 13 more
00:00 ERROR: [EOCVSim] The sim will exit now as it's impossible to continue execution without OpenCV
00:00  INFO: [Icons] Loading future icon ico_eocvsim
00:00  INFO: [CrashReport] Saved crash report to /Users/suds/crashreport-eocvsim-2021_12_10-10.55.01.log
suds@xxxx ~ % 

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Version 12.0.1

**Comment by serivesmejia** [comment]
Apologies for the issue. Can you try using the fix described in the comments of #63 ? Let me know how it goes !

**Comment by serivesmejia** [comment]
Closing for inactivity of this known issue, feel free to reopen or make another issue if you find another problem and I'll be happy to help :)
