### ISSUE TITLE
Make EOCV-Sim a module

### ISSUE THREAD

**Issue by AkarJosh** [deltacv/EOCV-Sim#78]
Our team uses kotlin so we cloned the eocv-sim repo as a separate branch in our repo.

Make EOCV-Sim a module like meepmeep.

**Comment by serivesmejia** [comment]
Apologies for the delayed response, apparently github doesn't like to email me

That's a great idea actually! It's quite simple because EOCV-Sim is already hosted in the same repo where meepmeep is so you can just pull it as a dependency like

```groovy
repositories {
     maven { url 'https://jitpack.com/' }
}

dependencies {
     implementation 'com.github.deltacv:EOCV-Sim:EOCV-Sim:3.2.2'
}
```

From there on you can just create a main function and initialize eocv sim:

```kotlin
fun main() = EOCVSim().start()
```

From there you just need to run that main function and it will automatically find your OpenCvPipeline-s in the module. I will add proper docs for this feature in the future, thanks so much for the idea!

**Comment by AkarJosh** [comment]
seems like .start() is private im using version 3.4.0 btw.

**Comment by serivesmejia** [comment]
> seems like .start() is private im using version 3.4.0 btw.

Oh yeah my bad, it's .init()

**Comment by AkarJosh** [comment]
Now im getting this error

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/opencv/core/Size
	at com.github.serivesmejia.eocvsim.EOCVSim.<clinit>(EOCVSim.kt:63)
	at MainKt.main(Main.kt:3)
	at MainKt.main(Main.kt)
Caused by: java.lang.ClassNotFoundException: org.opencv.core.Size
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 3 more

```

**Comment by serivesmejia** [comment]
Apologies for the lack of tracking on my end. If you still need help please open a new issue
