### ISSUE TITLE
Crashes when apriltags selected

### ISSUE THREAD

**Issue by foocross** [deltacv/EOCV-Sim#93]
Using on a mac m1.  I was able to start the app with:

 java -jar EOCV-Sim-3.4.3-all.jar

It crashed when I selected the AprilTag option.  Here is the crash report:

22.27.53.log
/--------------------------------\

  EOCV-Sim v3.4.3 crash report

\--------------------------------/

: Crash stacktrace

java.lang.ExceptionInInitializerError
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:375)
        at com.github.serivesmejia.eocvsim.pipeline.compiler.PipelineClassLoader.loadClass(PipelineClassLoader.kt:75)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at AprilTagDetectionPipeline.init(AprilTagDetectionPipeline.java:91)
        at com.github.serivesmejia.eocvsim.pipeline.PipelineManager$update$pipelineJob$1.invokeSuspend(PipelineManager.kt:258)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.UnsupportedOperationException: The native library failed to link, which probably means that the AprilTag plugin is not supported in the mac os x platform
        at io.github.deltacv.apriltag.NativeLibLoader.load(NativeLibLoader.java:97)
        at org.openftc.apriltag.AprilTagDetectorJNI.<clinit>(AprilTagDetectorJNI.java:105)
        ... 14 more
Caused by: java.lang.UnsatisfiedLinkError: /private/var/folders/62/39dnfkgj2752lzpcwpkxm13c0000gn/T/libapriltag.dylib: dlopen(/private/var/folders/62/39dnfkgj2752lzpcwpkxm13c0000gn/T/libapriltag.dylib, 0x0001): tried: '/private/var/folders/62/39dnfkgj2752lzpcwpkxm13c0000gn/T/libapriltag.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/62/39dnfkgj2752lzpcwpkxm13c0000gn/T/libapriltag.dylib' (no such file), '/private/var/folders/62/39dnfkgj2752lzpcwpkxm13c0000gn/T/libapriltag.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:384)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:228)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:170)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
        at java.base/java.lang.Runtime.load0(Runtime.java:755)
        at java.base/java.lang.System.load(System.java:1953)
        at io.github.deltacv.apriltag.NativeLibLoader.load(NativeLibLoader.java:95)
        ... 15 more

==========================================

: EOCV-Sim info
   Version: 3.4.3
   Built on: 2023-3-10 02:14:11

: System specs
   OS name: Mac OS X
   OS version: 13.2.1
   Detected OS: MACOS
   Arch: aarch64
   Detected Arch: ARMv8
   Java version: 17.0.1
   Java vendor: Azul Systems, Inc.
   Last memory usage: 161 MB

==========================================

: Full thread dump

 > Thread "FileWatcher-Workspace"
     java.base@17.0.1/java.lang.Thread.sleep(Native Method)
     app//com.github.serivesmejia.eocvsim.util.io.FileWatcher$Runner.run(FileWatcher.kt:94)
     java.base@17.0.1/java.lang.Thread.run(Thread.java:833)
 > Thread "Pipeline-AprilTagDetectionPipeline"
     java.base@17.0.1/java.lang.Thread.dumpThreads(Native Method)
     java.base@17.0.1/java.lang.Thread.getAllStackTraces(Thread.java:1662)
     app//com.github.serivesmejia.eocvsim.util.exception.handling.CrashReport.<init>(CrashReport.kt:97)
     app//com.github.serivesmejia.eocvsim.util.exception.handling.CrashReport.<init>(CrashReport.kt:40)
     app//com.github.serivesmejia.eocvsim.util.exception.handling.EOCVSimUncaughtExceptionHandler.uncaughtException(EOCVSimUncaughtExceptionHandler.kt:37)
     java.base@17.0.1/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1082)
     java.base@17.0.1/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1077)
     app//kotlinx.coroutines.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(CoroutineExceptionHandlerImpl.kt:39)
     app//kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:33)
     app//kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:241)
     app//kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:230)
     app//kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:925)
     app//kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:878)
     app//kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:843)
     app//kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:104)
     app//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
     app//kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
     java.base@17.0.1/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
     java.base@17.0.1/java.util.concurrent.FutureTask.run(FutureTask.java:264)
     java.base@17.0.1/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
     java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
     java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
     java.base@17.0.1/java.lang.Thread.run(Thread.java:833)
 > Thread "Common-Cleaner"
     java.base@17.0.1/java.lang.Object.wait(Native Method)
     java.base@17.0.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
     java.base@17.0.1/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140)
     java.base@17.0.1/java.lang.Thread.run(Thread.java:833)
     java.base@17.0.1/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:162)
 > Thread "main"
     java.base@17.0.1/jdk.internal.misc.Unsafe.park(Native Method)
     java.base@17.0.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
     app//kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:90)
     app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:61)
     app//kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
     app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:40)
     app//kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
     app//com.github.serivesmejia.eocvsim.pipeline.PipelineManager.update(PipelineManager.kt:310)
     app//com.github.serivesmejia.eocvsim.EOCVSim.start(EOCVSim.kt:224)
     app//com.github.serivesmejia.eocvsim.EOCVSim.init(EOCVSim.kt:208)
     app//com.github.serivesmejia.eocvsim.EOCVSimCommandInterface.run(Main.kt:53)
     app//picocli.CommandLine.executeUserObject(CommandLine.java:1939)
     app//picocli.CommandLine.access$1300(CommandLine.java:145)
     app//picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
     app//picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
     app//picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
     app//picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
     app//picocli.CommandLine.execute(CommandLine.java:2078)
     app//com.github.serivesmejia.eocvsim.Main.main(Main.kt:17)
 > Thread "DefaultDispatcher-worker-1"
     java.base@17.0.1/jdk.internal.misc.Unsafe.park(Native Method)
     java.base@17.0.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:376)
     app//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.park(CoroutineScheduler.kt:795)
     app//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.tryPark(CoroutineScheduler.kt:740)
     app//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:711)
     app//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
 > Thread "AppKit Thread"
 > Thread "DefaultDispatcher-worker-3"
     java.base@17.0.1/jdk.internal.misc.Unsafe.park(Native Method)
     java.base@17.0.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:376)
     app//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.park(CoroutineScheduler.kt:795)
     app//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.tryPark(CoroutineScheduler.kt:740)
     app//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:711)
     app//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
 > Thread "TimerQueue"
     java.base@17.0.1/jdk.internal.misc.Unsafe.park(Native Method)
     java.base@17.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
     java.base@17.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506)
     java.base@17.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463)
     java.base@17.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434)
     java.base@17.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623)
     java.base@17.0.1/java.util.concurrent.DelayQueue.take(DelayQueue.java:217)
     java.desktop@17.0.1/javax.swing.TimerQueue.run(TimerQueue.java:172)
     java.base@17.0.1/java.lang.Thread.run(Thread.java:833)
 > Thread "kotlinx.coroutines.DefaultExecutor"
     java.base@17.0.1/jdk.internal.misc.Unsafe.park(Native Method)
     java.base@17.0.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
     app//kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:82)
     java.base@17.0.1/java.lang.Thread.run(Thread.java:833)
 > Thread "Notification Thread"
 > Thread "Finalizer"
     java.base@17.0.1/java.lang.Object.wait(Native Method)
     java.base@17.0.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
     java.base@17.0.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
     java.base@17.0.1/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:172)
 > Thread "AWT-Shutdown"
     java.base@17.0.1/java.lang.Object.wait(Native Method)
     java.base@17.0.1/java.lang.Object.wait(Object.java:338)
     java.desktop@17.0.1/sun.awt.AWTAutoShutdown.run(AWTAutoShutdown.java:291)
     java.base@17.0.1/java.lang.Thread.run(Thread.java:833)
 > Thread "Signal Dispatcher"
 > Thread "AWT-EventQueue-0"
     java.base@17.0.1/jdk.internal.misc.Unsafe.park(Native Method)
     java.base@17.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
     java.base@17.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506)
     java.base@17.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463)
     java.base@17.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434)
     java.base@17.0.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623)
     java.desktop@17.0.1/java.awt.EventQueue.getNextEvent(EventQueue.java:567)
     java.desktop@17.0.1/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:190)
     java.desktop@17.0.1/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
     java.desktop@17.0.1/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
     java.desktop@17.0.1/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
     java.desktop@17.0.1/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
     java.desktop@17.0.1/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
 > Thread "MatPoster-Viewport-Thread"
     app//com.github.serivesmejia.eocvsim.gui.util.MatPoster$PosterRunnable.run(MatPoster.java:190)
     java.base@17.0.1/java.lang.Thread.run(Thread.java:833)
 > Thread "Java2D Disposer"
     java.base@17.0.1/java.lang.Object.wait(Native Method)
     java.base@17.0.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
     java.base@17.0.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
     java.desktop@17.0.1/sun.java2d.Disposer.run(Disposer.java:145)
     java.base@17.0.1/java.lang.Thread.run(Thread.java:833)
 > Thread "Reference Handler"
     java.base@17.0.1/java.lang.ref.Reference.waitForReferencePendingList(Native Method)
     java.base@17.0.1/java.lang.ref.Reference.processPendingReferences(Reference.java:253)
     java.base@17.0.1/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:215)
 > Thread "DefaultDispatcher-worker-2"
     java.base@17.0.1/jdk.internal.misc.Unsafe.park(Native Method)
     java.base@17.0.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:376)
     app//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.park(CoroutineScheduler.kt:795)
     app//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.tryPark(CoroutineScheduler.kt:740)
     app//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:711)
     app//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
 > Thread "Java2D Queue Flusher"
     java.base@17.0.1/java.lang.Object.wait(Native Method)
     java.desktop@17.0.1/sun.java2d.opengl.OGLRenderQueue$QueueFlusher.run(OGLRenderQueue.java:206)
     java.base@17.0.1/java.lang.Thread.run(Thread.java:833)

==================================

: Full logs

[22:27:51] [main/TRACE]: [LockFile] Probably locked file /Users/hoa/.eocvsim/.lock
[22:27:51] [main/INFO]: [EOCVSim] Confirmed claiming of the lock file in /Users/hoa/.eocvsim
[22:27:51] [main/INFO]: [EOCVSim] -- Initializing EasyOpenCV Simulator v3.4.3 (4f5991f6) --
[22:27:51] [AWT-EventQueue-0/TRACE]: [Icons] Loading future icon ico_eocvsim
[22:27:51] [main/INFO]: [EOCVSim] Successfully loaded the OpenCV native lib
[22:27:52] [main/INFO]: [ConfigManager] Initializing...
[22:27:52] [DefaultDispatcher-worker-1/INFO]: [ClasspathScan] Starting to scan classpath...
[22:27:52] [main/INFO]: [ConfigManager] Loaded config from file successfully
[22:27:52] [main/INFO]: [WorkspaceManager] Set current workspace to /Users/hoa/.eocvsim/default_workspace
[22:27:52] [main/INFO]: [WorkspaceManager] Loaded workspace config successfully
[22:27:52] [FileWatcher-Workspace/INFO]: [FileWatcher-Workspace] Starting to watch directories in:
/Users/hoa/.eocvsim/default_workspace
/Users/hoa/.eocvsim/default_workspace

[22:27:52] [main/INFO]: [WorkspaceManager] Loaded workspace config successfully
[22:27:52] [main/INFO]: [InputSourceManager] Initializing...
[22:27:52] [main/INFO]: [InputSourceManager] Adding InputSource ImageSource("/var/folders/62/39dnfkgj2752lzpcwpkxm13c0000gn/T/ug_eocvsim_4.jpg", 320x240) (ImageSource)
[22:27:52] [main/INFO]: [InputSourceManager] Adding InputSource ImageSource("/var/folders/62/39dnfkgj2752lzpcwpkxm13c0000gn/T/ug_eocvsim_1.jpg", 320x240) (ImageSource)
[22:27:52] [main/INFO]: [InputSourceManager] Adding InputSource ImageSource("/var/folders/62/39dnfkgj2752lzpcwpkxm13c0000gn/T/ug_eocvsim_0.jpg", 320x240) (ImageSource)
[22:27:52] [main/INFO]: [InputSourceManager] Set InputSource to ImageSource("/var/folders/62/39dnfkgj2752lzpcwpkxm13c0000gn/T/ug_eocvsim_4.jpg", 320x240) (ImageSource)
[22:27:52] [main/INFO]: [InputSourceLoader] InputSources file version is DOS
[22:27:52] [main/INFO]: [PipelineManager] Initializing...
[22:27:52] [main/INFO]: [CompiledPipelineManager] Initializing...
[22:27:52] [DefaultDispatcher-worker-3/INFO]: [WorkspaceManager] Loaded workspace config successfully
[22:27:52] [DefaultDispatcher-worker-3/INFO]: [CompiledPipelineManager] Building java files in workspace, at /Users/hoa/.eocvsim/default_workspace
[22:27:52] [DefaultDispatcher-worker-3/TRACE]: [PipelineStandardFileManager] Scanning classpath files...
[22:27:52] [DefaultDispatcher-worker-3/TRACE]: [PipelineStandardFileManager] Found classpath file /Users/hoa/code/ftc/eocv/EOCV-Sim-3.4.3-all.jar
[22:27:52] [DefaultDispatcher-worker-1/INFO]: [ClasspathScan] ClassGraph finished scanning (took 0.703793709s)
[22:27:52] [DefaultDispatcher-worker-1/INFO]: [ClasspathScan] Found 0 pipelines
[22:27:52] [DefaultDispatcher-worker-1/TRACE]: [ClasspathScan] Found tunable field com.github.serivesmejia.eocvsim.tuner.field.BooleanField
[22:27:52] [DefaultDispatcher-worker-1/TRACE]: [ClasspathScan] Found tunable field com.github.serivesmejia.eocvsim.tuner.field.EnumField
[22:27:52] [DefaultDispatcher-worker-1/TRACE]: [ClasspathScan] Found acceptor for this tunable field, com.github.serivesmejia.eocvsim.tuner.field.EnumField
[22:27:52] [DefaultDispatcher-worker-1/TRACE]: [ClasspathScan] Found tunable field com.github.serivesmejia.eocvsim.tuner.field.StringField
[22:27:52] [DefaultDispatcher-worker-1/TRACE]: [ClasspathScan] Found tunable field com.github.serivesmejia.eocvsim.tuner.field.cv.PointField
[22:27:52] [DefaultDispatcher-worker-1/TRACE]: [ClasspathScan] Found tunable field com.github.serivesmejia.eocvsim.tuner.field.cv.RectField
[22:27:52] [DefaultDispatcher-worker-1/TRACE]: [ClasspathScan] Found tunable field com.github.serivesmejia.eocvsim.tuner.field.cv.ScalarField
[22:27:52] [DefaultDispatcher-worker-1/TRACE]: [ClasspathScan] Found tunable field com.github.serivesmejia.eocvsim.tuner.field.numeric.DoubleField
[22:27:52] [DefaultDispatcher-worker-1/TRACE]: [ClasspathScan] Found tunable field com.github.serivesmejia.eocvsim.tuner.field.numeric.FloatField
[22:27:52] [DefaultDispatcher-worker-1/TRACE]: [ClasspathScan] Found tunable field com.github.serivesmejia.eocvsim.tuner.field.numeric.IntegerField
[22:27:52] [DefaultDispatcher-worker-1/TRACE]: [ClasspathScan] Found tunable field com.github.serivesmejia.eocvsim.tuner.field.numeric.LongField
[22:27:52] [DefaultDispatcher-worker-1/TRACE]: [ClasspathScan] Found 10 tunable fields and 1 acceptors
[22:27:52] [DefaultDispatcher-worker-1/INFO]: [ClasspathScan] Finished scanning (took 0.707149125s)
[22:27:52] [main/INFO]: [PipelineManager] Found 1 pipeline(s)
[22:27:52] [AWT-EventQueue-0/TRACE]: [Icons] Loading future icon ico_colorpick_pointer
[22:27:52] [AWT-EventQueue-0/TRACE]: [Icons] Loading future icon ico_img
[22:27:52] [main/INFO]: [EOCVSim] -- Begin EOCVSim loop (4f5991f6) --
[22:27:53] [main/INFO]: [PipelineManager] Changing to pipeline com.github.serivesmejia.eocvsim.pipeline.DefaultPipeline
[22:27:53] [main/INFO]: [PipelineManager] Instantiated pipeline class com.github.serivesmejia.eocvsim.pipeline.DefaultPipeline
[22:27:53] [main/INFO]: [PipelineSnapshot] Taken snapshot of pipeline com.github.serivesmejia.eocvsim.pipeline.DefaultPipeline
[22:27:53] [main/TRACE]: [Icons] Loading future icon ico_slider
[22:27:53] [main/TRACE]: [Icons] Loading future icon ico_config
[22:27:53] [DefaultDispatcher-worker-3/TRACE]: [CompiledPipelineManager] Looking for pipelines in jar file /Users/hoa/.eocvsim/compiler/out_jars/pipelines.jar
[22:27:53] [DefaultDispatcher-worker-3/INFO]: [ClasspathScan] Starting to scan for classes in /Users/hoa/.eocvsim/compiler/out_jars/pipelines.jar...
[22:27:53] [DefaultDispatcher-worker-3/INFO]: [ClasspathScan] ClassGraph finished scanning (took 0.007325375s)
[22:27:53] [DefaultDispatcher-worker-3/INFO]: [ClasspathScan] Found pipeline AprilTagDetectionPipeline
[22:27:53] [DefaultDispatcher-worker-3/INFO]: [ClasspathScan] Found pipeline SimpleThresholdPipeline
[22:27:53] [DefaultDispatcher-worker-3/INFO]: [ClasspathScan] Found pipeline SkystoneDeterminationPipeline
[22:27:53] [DefaultDispatcher-worker-3/INFO]: [ClasspathScan] Found pipeline StageSwitchingPipeline
[22:27:53] [DefaultDispatcher-worker-3/INFO]: [ClasspathScan] Found pipeline StoneOrientationAnalysisPipeline
[22:27:53] [DefaultDispatcher-worker-3/INFO]: [ClasspathScan] Found 5 pipelines
[22:27:53] [DefaultDispatcher-worker-3/TRACE]: [ClasspathScan] Found 0 tunable fields and 0 acceptors
[22:27:53] [DefaultDispatcher-worker-3/INFO]: [ClasspathScan] Finished scanning (took 0.011993959s)
[22:27:53] [DefaultDispatcher-worker-3/TRACE]: [CompiledPipelineManager] Added AprilTagDetectionPipeline from jar
[22:27:53] [DefaultDispatcher-worker-3/TRACE]: [CompiledPipelineManager] Added SimpleThresholdPipeline from jar
[22:27:53] [DefaultDispatcher-worker-3/TRACE]: [CompiledPipelineManager] Added SkystoneDeterminationPipeline from jar
[22:27:53] [DefaultDispatcher-worker-3/TRACE]: [CompiledPipelineManager] Added StageSwitchingPipeline from jar
[22:27:53] [DefaultDispatcher-worker-3/TRACE]: [CompiledPipelineManager] Added StoneOrientationAnalysisPipeline from jar
[22:27:53] [DefaultDispatcher-worker-3/INFO]: [CompiledPipelineManager] Build successful (took 0.80 seconds)

Using the JDK compiler

> AprilTagDetectionPipeline.java
      (95:17): MANDATORY_WARNING: finalize() in java.lang.Object has been deprecated

[22:27:53] [main/TRACE]: [Icons] Loading future icon ico_colorpick
[22:27:53] [AWT-EventQueue-0/TRACE]: [Icons] Loading future icon ico_hammer
[22:27:53] [AWT-EventQueue-0/TRACE]: [Icons] Loading future icon ico_gears
[22:27:53] [Pipeline-DefaultPipeline/INFO]: [PipelineManager] Initialized pipeline DefaultPipeline
[22:27:53] [main/INFO]: [PipelineSnapshot] Taken snapshot of pipeline com.github.serivesmejia.eocvsim.pipeline.DefaultPipeline
[22:27:53] [main/INFO]: [PipelineManager] Changing to pipeline AprilTagDetectionPipeline
[22:27:53] [main/INFO]: [PipelineManager] Instantiated pipeline class AprilTagDetectionPipeline
[22:27:53] [main/INFO]: [PipelineSnapshot] Taken snapshot of pipeline AprilTagDetectionPipeline
[22:27:53] [main/TRACE]: [Icons] Loading future icon ico_textbox
[22:27:53] [Pipeline-AprilTagDetectionPipeline/ERROR]: [EOCVSimUncaughtExceptionHandler] Uncaught exception thrown in "Pipeline-AprilTagDetectionPipeline" thread
java.lang.ExceptionInInitializerError: null
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at com.github.serivesmejia.eocvsim.pipeline.compiler.PipelineClassLoader.loadClass(PipelineClassLoader.kt:75) ~[EOCV-Sim-3.4.3-all.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at AprilTagDetectionPipeline.init(AprilTagDetectionPipeline.java:91) ~[?:?]
        at com.github.serivesmejia.eocvsim.pipeline.PipelineManager$update$pipelineJob$1.invokeSuspend(PipelineManager.kt:258) ~[EOCV-Sim-3.4.3-all.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [EOCV-Sim-3.4.3-all.jar:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [EOCV-Sim-3.4.3-all.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.UnsupportedOperationException: The native library failed to link, which probably means that the AprilTag plugin is not supported in the mac os x platform
        at io.github.deltacv.apriltag.NativeLibLoader.load(NativeLibLoader.java:97) ~[EOCV-Sim-3.4.3-all.jar:?]
        at org.openftc.apriltag.AprilTagDetectorJNI.<clinit>(AprilTagDetectorJNI.java:105) ~[EOCV-Sim-3.4.3-all.jar:?]
        ... 14 more
Caused by: java.lang.UnsatisfiedLinkError: /private/var/folders/62/39dnfkgj2752lzpcwpkxm13c0000gn/T/libapriltag.dylib: dlopen(/private/var/folders/62/39dnfkgj2752lzpcwpkxm13c0000gn/T/libapriltag.dylib, 0x0001): tried: '/private/var/folders/62/39dnfkgj2752lzpcwpkxm13c0000gn/T/libapriltag.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/62/39dnfkgj2752lzpcwpkxm13c0000gn/T/libapriltag.dylib' (no such file), '/private/var/folders/62/39dnfkgj2752lzpcwpkxm13c0000gn/T/libapriltag.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
        at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
        at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:384) ~[?:?]
        at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:228) ~[?:?]
        at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:170) ~[?:?]
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389) ~[?:?]
        at java.lang.Runtime.load0(Runtime.java:755) ~[?:?]
        at java.lang.System.load(System.java:1953) ~[?:?]
        at io.github.deltacv.apriltag.NativeLibLoader.load(NativeLibLoader.java:95) ~[EOCV-Sim-3.4.3-all.jar:?]
        at org.openftc.apriltag.AprilTagDetectorJNI.<clinit>(AprilTagDetectorJNI.java:105) ~[EOCV-Sim-3.4.3-all.jar:?]
        ... 14 more

**Comment by foocross** [comment]
Found the answer by looking at resolved issues.  Sorry to bother you.
